trigger:
- none

variables:
  DeploymentPath: 'C:\Deployments\AzureTestProject'

resources:
  pipelines:
    - pipeline: 'buildPipeline'
      project: 'AzureTestProject'
      source: 'Build pipeline'
      branch: 'main'

stages:
  - stage: DeployWebsite
    displayName: 'Deploy website'
    pool:
      vmImage: windows-latest

    jobs:
    - deployment: DeployWebsite
      displayName: 'Deploy website'
      environment: 'Windows 11 server.DESLAB-052'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: none

              - download: 'buildPipeline'
                name: 'DownloadBuildArtifacts'
                displayName: 'Download Build Artifacts'
                artifact: 'AzureTestProject'

              - powershell: |
                  $ErrorActionPreference = "Stop"
                  Write-Host "Deploying application..."
                  
                  if (!(Test-Path "$(DeploymentPath)")) {
                      New-Item -ItemType Directory -Path "$(DeploymentPath)" -Force
                  }
                  
                  Copy-Item "$(Pipeline.Workspace)\buildPipeline\AzureTestProject\*" "$(DeploymentPath)" -Recurse -Force
                  
                  Write-Host "Deployment complete."
                displayName: 'Copy Build Artifacts to Deployment Directory'
